### ISSUE TITLE
Error Running in Deepstream 6.0

### ISSUE THREAD

**Issue by muhammadabdullah34907** [Ryoyo-NV/Gaze-Analysis-System#1]
This is the below error I am facing while running on jetpack 4.6 and deepstream 6.0. 

```
Traceback (most recent call last):
  File "run_gaze_sequential.py", line 11, in <module>
    from face_landmark import FaceLandmarkEngine, FaceLandmarkPost, FaceLandmarkDraw, leye_boxes, reye_boxes
  File "/home/cvision/Gaze-Analysis-System/face_landmark.py", line 11, in <module>
    ctypes.CDLL(os.path.join(os.getcwd(), "libflnetsoftargmax.so"))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/cvision/Gaze-Analysis-System/libflnetsoftargmax.so: cannot open shared object file: No such file or directory

```

**Comment by takutoi** [comment]
Sorry for my late reply.
The setup.sh fails to build libflnetsoftargmax.so due to some changes of TensorRT 8 in JetPack 4.6.
So please use JetPack 4.5.1 or earlier.
